"""Takes a class list generated by Wesley -- new version, with UTOR
IDs. Produces a classlist I use for my own purposes. Takes a
filename. Writes output to stdout. Output format is:

UTOR_ID,student-number,last-name,first-name0 first-name1 ...

Input file format is:

CourseCode|StudentNumber|UTORid|FirstName(s) LastName|Type|
"""

import sys

def utsc_to_classlist(in_file):
    """Takes a valid file object. Writes to stdout."""

    for line in in_file:
        tokens = line.strip().split('|')
        
        if len(tokens) < 6:
            print("Something wrong with input file. Good bye!")
            return
        utorid = tokens[2]
        student_num = tokens[1][1:]
        names = tokens[3].split()
        first_names = ' '.join(names[:-1])
        last_name = names[-1]
        print ','.join([utorid, student_num, last_name, first_names])

def main():
    """Try to open input file. Process."""

    if len(sys.argv) != 2:
        print("Usage: python utsc2classlist.py <UTSC-classlist>")
        exit(1)

    utsc_to_classlist(open(sys.argv[1]))

if __name__ == '__main__':

    main()
        
