"""Takes a class list generated by Wesley. Produces a classlist I use
for my own purposes. Takes a filename. Writes output to stdout. Output
format is:

UTSC-login,student-number,last-name,first-name0 first-name1 ...

Input file format is:

useradd students <UTSC-login> <id> "0<student-number> <firstname0> ... <lastname>"

"""

import sys

def utsc_to_classlist(in_file):
    """Takes a valid file object. Writes to stdout."""

    for line in in_file:
        tokens = line.split()
        
        if len(tokens) < 7:
            print("Something wrong with input file. Good bye!")
            return
        
        print(tokens[2] + ',' +
              tokens[4][2:] + ',' +
              tokens[-1][:-1] + ',' +
              ' '.join(tokens[5:-1]))

def main():
    """Try to open input file. Process."""

    if len(sys.argv) != 2:
        print("Usage: python utsc2classlist.py <UTSC-classlist>")
        exit(1)

    utsc_to_classlist(open(sys.argv[1]))

if __name__ == '__main__':

    main()
        
